# Generated by Django 3.1.5 on 2021-06-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='subdirname',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='Main_Img',
            field=models.ImageField(upload_to='images/%m%d/'),
        ),
    ]
